### Listing all resources
GET http://localhost:3000/api/products

### Getting a resource

GET http://localhost:3000/api/products?id=1

### Creating a resource

POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name" : "T_shirt",
    "price" : 20000,
    "category" : "fashion"
}

###
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name" : "Raket",
    "price" : 20000,
    "category" : "olahraga"
}

### udpate all data (name, price, category, is_available
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
    "name" : "Bunga",
    "price" : 50000,
    "category" : "decoration",
    "is_available" : false
}
### just update is available
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
    "name" : "Bunga",
    "price" : 50000,
    "category" : "decoration",
    "is_available" : false
}


### delete data 
DELETE  http://localhost:3000/api/products/1
Content-Type: application/json
